// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/21/2026, 2:06:42 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/cris/Desktop/forge_web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/plugins/**/*.{js,ts,mjs}","/Users/cris/Desktop/forge_web/app/stores/**/*.{js,ts,mjs}","/Users/cris/Desktop/forge_web/app/composables/**/*.{js,ts,mjs}","/Users/cris/Desktop/forge_web/app/utils/**/*.{js,ts,mjs}","/Users/cris/Desktop/forge_web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/cris/Desktop/forge_web/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;