// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/7/2026, 20:01:51
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/plugins/**/*.{js,ts,mjs}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/stores/**/*.{js,ts,mjs}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/composables/**/*.{js,ts,mjs}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/utils/**/*.{js,ts,mjs}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/crist/Desktop/Proyectos/Forge/Forge_web/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;